version: '3'
services:
  housthon:
    container_name: housthon
    build:
      context: ./context/
    environment:
          COLISSITHON_IP: 192.168.0.31
          COLISSITHON_PORT: 9876
          HOUSTHON_PORT: 8090
          KAFKA_IP: 192.168.0.31
          KAFKA_PORT: 8092
          TOPIC_TWITTHON: housToTwit
          TOPIC_TRAVELTHON: housToTravel
          TOPIC_GOOGLETHON: housToGoogle
          TOPIC_COMPARATHON: housToCompara
          PATH_TWEET: /app/samples/tweets
          PATH_PICTURES: /app/samples/pictures
    ports:
    - "8090:8090"

