version: '3'
services:
  housthon:
    image: reachhubcorp/housthon:latest
    container_name: housthon
#    build:
#      context: ./context/
    environment:
          HOUSTHON_PORT: 8090
          COLISSITHON_IP: "${ipcolissithon}"
          COLISSITHON_PORT: 9876
          KAFKA_IP: "${ipkafka}"
          KAFKA_PORT: 8092
          TOPIC_GOOGLETHON: housToGoogle
          FTP_IP: "${ftpip}"
          FTP_PORT: 21
          FTP_ID: ${ftpid}
          FTP_PASSWORD: ${ftppassword}
          FTP_PATH: ${ftppath}
          PATH_PICTURES: /app/samples/pictures
    ports:
       - "8090:8090"

