version: '3'
services:
  housthon:
    build:
      context: ./context/
    environment:
          COLISSITHON_IP: 192.168.0.40
          COLISSITHON_PORT: 9876
          HOUSTHON_PORT: 8090
          KAFKA_IP: 192.168.0.40
          KAFKA_PORT: 8092
          TOPIC_TWITTHON: tweethon
          TOPIC_TRAVELTHON: travelthon
          TOPIC_COMPARATHON: comparathon
          TOPIC_GOOGLETHON: googlethon
          PATH_TWEET: /app/samples/tweets
          PATH_PICTURES: /app/samples/pictures
    ports:
    - "8090:8090"

