version: '3'
services:
  housthon:
    build:
      context: ./context/
    environment:
          COLISSITHON_IP: colissithon-ip
          COLISSITHON_PORT: 9876
          HOUSTHON_PORT: 8090
          KAFKA_IP: kafka-ip
          KAFKA_PORT: 8092
          TOPIC_TWITTHON: housToTwit
          TOPIC_TRAVELTHON: housToTravel
          TOPIC_GOOGLETHON: housToGoogle
          topic_housTOcompara: housToCompara
          PATH_TWEET: /app/samples/tweets
          PATH_PICTURES: /app/samples/pictures
    ports:
    - "8090:8090"

