version: '3'
services:
 #BROKER
 zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - 2181:2181
      networks:
        - reach
 kafka:
      image: wurstmeister/kafka:latest
      container_name: kafka
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 192.168.0.13
        KAFKA_ADVERTISED_PORT: 8092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "tweetopic:1:1,topictures:1:1"
      ports:
        - 8092:9092
      networks:
        - reach
networks:
  reach:
    driver: bridge